export LC_ALL="C"
export ALLOW_MISSING_DEPENDENCIES=true

export FOX_USE_NANO_EDITOR=1
export FOX_USE_TAR_BINARY=1
export FOX_REPLACE_BUSYBOX_PS=1
export FOX_ASH_IS_BASH=1
export FOX_USE_BASH_SHELL=1
export FOX_VARIANT="FBE"

export OF_ALLOW_DISABLE_NAVBAR=0
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export OF_SKIP_MULTIUSER_FOLDERS_BACKUP=1
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_CHECK_OVERWRITE_ATTEMPTS=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=1
export OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR=1

export FOX_ADVANCED_SECURITY=1
export OF_USE_TWRP_SAR_DETECT=1
export OF_QUICK_BACKUP_LIST="/boot;/data;/system_image;/vendor_image;"

export OF_FLASHLIGHT_ENABLE=0
export OF_SCREEN_H=1920
export OF_STATUS_H=80
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48

add_lunch_combo omni_clover-eng
